name: "Lint"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      
    steps:
      - name: Checkout code
      - uses: actions/checkout@v1
      
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
